/* auto-generated by NAPI-RS */
/* eslint-disable */
export type {
  CanonicalSchemaBytesLiteral,
  CanonicalSchemaLiteral,
  CanonicalSchemaMapLiteral,
  CanonicalSchemaUIntLiteral,
  DenseVectorSchema,
  EdgeSchema,
  EdgeSchemaInfo,
  EdgeValiditySchema,
  EndpointLabelSchema,
  GraphSchema,
  GraphSchemaCheckReport,
  GraphSchemaDropAction,
  GraphSchemaDropTargetResult,
  GraphSchemaEdgeEntry,
  GraphSchemaNodeEntry,
  GraphSchemaOperation,
  GraphSchemaOperationKind,
  GraphSchemaPublishResult,
  GraphSchemaTargetKind,
  GraphSchemaValidationReportEntry,
  NodeLabelConstraintSchema,
  NodeSchema,
  NodeSchemaInfo,
  NumericFieldSchema,
  PropertySchema,
  SchemaAdditionalProperties,
  SchemaBytesLiteral,
  SchemaLiteral,
  SchemaMapLiteral,
  SchemaNumericBound,
  SchemaUIntLiteral,
  SchemaValidationReport,
  SchemaValueType,
  SchemaVectorPresence,
  SchemaViolation,
  SchemaViolationTarget,
  SparseVectorSchema,
  StringFieldSchema,
} from './schema-types'
export declare class EdgePageResult {
  get items(): Array<EdgeView>
  get nextCursor(): number | null
}

/**
 * Edge view: eager primitives, lazy props. Props are Arc-shared so
 * container getters (page results, subgraph) avoid cloning the BTreeMap.
 */
export declare class EdgeView {
  get id(): number
  get from(): number
  get to(): number
  get label(): string
  get props(): Record<string, any>
  get createdAt(): number
  get updatedAt(): number
  get weight(): number
  get validFrom(): number
  get validTo(): number
}

export declare class NeighborPageResult {
  get items(): Array<NeighborEntry>
  get nextCursor(): number | null
}

export declare class NodePageResult {
  get items(): Array<NodeView>
  get nextCursor(): number | null
}

/**
 * Node view: eager primitives, lazy props. Props are Arc-shared so
 * container getters (page results, subgraph) avoid cloning the BTreeMap.
 */
export declare class NodeView {
  get id(): number
  get labels(): Array<string>
  get key(): string
  get props(): Record<string, any>
  get createdAt(): number
  get updatedAt(): number
  get weight(): number
  get denseVector(): Array<number> | null
  get sparseVector(): Array<SparseEntry> | null
}

export declare class OverGraph {
  static open(path: string, options?: DbOptions | undefined | null): OverGraph
  close(options?: CloseOptions | undefined | null): void
  ensureNodeLabel(label: string): number
  ensureEdgeLabel(label: string): number
  getNodeLabelId(label: string): number | null
  getEdgeLabelId(label: string): number | null
  getNodeLabel(labelId: number): string | null
  getEdgeLabel(labelId: number): string | null
  listNodeLabels(): Array<NodeLabelInfo>
  listEdgeLabels(): Array<EdgeLabelInfo>
  setNodeSchema(label: string, schema: import('./schema-types').NodeSchema, options?: SchemaSetOptions | null): import('./schema-types').NodeSchemaInfo
  checkNodeSchema(label: string, schema: import('./schema-types').NodeSchema, options?: SchemaCheckOptions | null): import('./schema-types').SchemaValidationReport
  dropNodeSchema(label: string): boolean
  getNodeSchema(label: string): import('./schema-types').NodeSchemaInfo | null
  listNodeSchemas(): Array<import('./schema-types').NodeSchemaInfo>
  setEdgeSchema(label: string, schema: import('./schema-types').EdgeSchema, options?: SchemaSetOptions | null): import('./schema-types').EdgeSchemaInfo
  checkEdgeSchema(label: string, schema: import('./schema-types').EdgeSchema, options?: SchemaCheckOptions | null): import('./schema-types').SchemaValidationReport
  dropEdgeSchema(label: string): boolean
  getEdgeSchema(label: string): import('./schema-types').EdgeSchemaInfo | null
  listEdgeSchemas(): Array<import('./schema-types').EdgeSchemaInfo>
  setGraphSchema(schema: import('./schema-types').GraphSchema, options?: SchemaSetOptions | null): import('./schema-types').GraphSchemaPublishResult
  alterGraphSchema(operations: Array<import('./schema-types').GraphSchemaOperation>, options?: SchemaSetOptions | null): import('./schema-types').GraphSchemaPublishResult
  checkGraphSchemaSet(schema: import('./schema-types').GraphSchema, options?: SchemaCheckOptions | null): import('./schema-types').GraphSchemaCheckReport
  checkGraphSchemaAdd(schema: import('./schema-types').GraphSchema, options?: SchemaCheckOptions | null): import('./schema-types').GraphSchemaCheckReport
  dropGraphSchema(): import('./schema-types').GraphSchemaPublishResult
  upsertNode(labels: string | string[], key: string, options?: UpsertNodeOptions | null): number
  addNodeLabel(nodeId: number, label: string): boolean
  removeNodeLabel(nodeId: number, label: string): boolean
  upsertEdge(from: number, to: number, label: string, options?: UpsertEdgeOptions | undefined | null): number
  batchUpsertNodes(nodes: Array<NodeInput>): Float64Array
  batchUpsertEdges(edges: Array<EdgeInput>): Float64Array
  /**
   * Batch upsert nodes from a packed binary Buffer. See `packNodeBatch()` in JS.
   *
   * Binary format (little-endian):
   *   [magic: 4 bytes "OGNB"][version: u16 = 2][count: u32]
   *   per node:
   *     [label_count: u8] repeated [label_len: u16][label: utf8][weight: f32]
   *     [key_len: u16][key: utf8][props_len: u32][props: json utf8]
   */
  batchUpsertNodesBinary(buffer: Buffer): Float64Array
  /**
   * Batch upsert edges from a packed binary Buffer. See `packEdgeBatch()` in JS.
   *
   * Binary format (little-endian):
   *   [magic: 4 bytes "OGEB"][version: u16 = 1][count: u32]
   *   per edge:
   *     [from: u64][to: u64][label_len: u16][label: utf8][weight: f32]
   *     [valid_from: i64][valid_to: i64][props_len: u32][props: json utf8]
   * In this packed format, valid_from=0 and valid_to=0 are sentinels for
   * engine defaults (created_at and no expiration), not explicit epoch 0.
   */
  batchUpsertEdgesBinary(buffer: Buffer): Float64Array
  getNode(id: number): NodeView | null
  getEdge(id: number): EdgeView | null
  getNodeByKey(label: string, key: string): NodeView | null
  getEdgeByTriple(from: number, to: number, label: string): EdgeView | null
  getNodes(ids: Array<number>): Array<NodeView | undefined | null>
  getNodesByKeys(keys: Array<KeyQuery>): Array<NodeView | undefined | null>
  getEdges(ids: Array<number>): Array<EdgeView | undefined | null>
  deleteNode(id: number): void
  deleteEdge(id: number): void
  invalidateEdge(id: number, validTo: number): EdgeView | null
  graphPatch(patch: GraphPatch): PatchResult
  beginWriteTxn(): WriteTxn
  beginWriteTxnAsync(): Promise<WriteTxn>
  prune(policy: PrunePolicy): PruneResult
  setPrunePolicy(name: string, policy: PrunePolicy): void
  removePrunePolicy(name: string): boolean
  listPrunePolicies(): Array<NamedPrunePolicy>
  setPrunePolicyAsync(name: string, policy: PrunePolicy): Promise<void>
  removePrunePolicyAsync(name: string): Promise<boolean>
  listPrunePoliciesAsync(): Promise<Array<NamedPrunePolicy>>
  neighbors(nodeId: number, options?: NeighborsOptions | undefined | null): Array<NeighborEntry>
  traverse(startNodeId: number, maxDepth: number, options?: TraverseOptions | undefined | null): TraversalPageResult
  topKNeighbors(nodeId: number, k: number, options?: TopKNeighborsOptions | undefined | null): Array<NeighborEntry>
  extractSubgraph(startNodeId: number, maxDepth: number, options?: ExtractSubgraphOptions | undefined | null): SubgraphResult
  /**
   * Batch neighbor query: fetch neighbors for multiple nodes in one call.
   * Returns an array of entries, each mapping a query node to its neighbors.
   */
  neighborsBatch(nodeIds: Array<number>, options?: NeighborsBatchOptions | undefined | null): Array<NeighborBatchEntry>
  degree(nodeId: number, options?: DegreeOptions | undefined | null): number
  sumEdgeWeights(nodeId: number, options?: SumEdgeWeightsOptions | undefined | null): number
  avgEdgeWeight(nodeId: number, options?: AvgEdgeWeightOptions | undefined | null): number | null
  degrees(nodeIds: Array<number>, options?: DegreesOptions | undefined | null): Array<DegreeBatchEntry>
  shortestPath(from: number, to: number, options?: ShortestPathOptions | undefined | null): ShortestPath | null
  isConnected(from: number, to: number, options?: IsConnectedOptions | undefined | null): boolean
  allShortestPaths(from: number, to: number, options?: AllShortestPathsOptions | undefined | null): Array<ShortestPath>
  findNodes(label: string, propKey: string, propValue: any): Float64Array
  queryNodeIds(request: import('./query-types').QueryNodeRequest): IdPageResult
  queryNodes(request: import('./query-types').QueryNodeRequest): NodePageResult
  queryEdgeIds(request: import('./query-types').QueryEdgeRequest): IdPageResult
  queryEdges(request: import('./query-types').QueryEdgeRequest): EdgePageResult
  queryGraphRows(request: import('./query-types').GraphRowRequest): import('./query-types').GraphRowResult
  queryGraphPipeline(request: import('./query-types').GraphPipelineRequest): import('./query-types').GraphPipelineResult
  explainNodeQuery(request: import('./query-types').QueryNodeRequest): import('./query-types').QueryPlan
  explainEdgeQuery(request: import('./query-types').QueryEdgeRequest): import('./query-types').QueryPlan
  explainGraphRows(request: import('./query-types').GraphRowRequest): import('./query-types').GraphRowExplain
  explainGraphPipeline(request: import('./query-types').GraphPipelineRequest): import('./query-types').GraphPipelineExplain
  executeGql(query: string, params?: import('./query-types').GqlParams | null, options?: import('./query-types').GqlExecutionOptions | null): import('./query-types').GqlExecutionResult
  explainGql(query: string, params?: import('./query-types').GqlParams | null, options?: import('./query-types').GqlExecutionOptions | null): import('./query-types').GqlExecutionExplain
  ensureNodePropertyIndex(label: string, spec: SecondaryIndexSpec): NodePropertyIndexInfo
  dropNodePropertyIndex(label: string, spec: SecondaryIndexSpec): boolean
  listNodePropertyIndexes(): Array<NodePropertyIndexInfo>
  ensureEdgePropertyIndex(label: string, spec: SecondaryIndexSpec): EdgePropertyIndexInfo
  dropEdgePropertyIndex(label: string, spec: SecondaryIndexSpec): boolean
  listEdgePropertyIndexes(): Array<EdgePropertyIndexInfo>
  /** Return all node IDs containing every supplied node label (unpaged). */
  nodesByLabels(labels: string | string[]): Float64Array
  /** Return all edge IDs of a given label (unpaged). */
  edgesByLabel(label: string): Float64Array
  getNodesByLabels(labels: string | string[]): Array<NodeView>
  getEdgesByLabel(label: string): Array<EdgeView>
  countNodesByLabels(labels: string | string[]): number
  countEdgesByLabel(label: string): number
  nodesByLabelsPaged(labels: string | string[], limit?: number | null, after?: number | null): IdPageResult
  edgesByLabelPaged(label: string, limit?: number | undefined | null, after?: number | undefined | null): IdPageResult
  getNodesByLabelsPaged(labels: string | string[], limit?: number | null, after?: number | null): NodePageResult
  getEdgesByLabelPaged(label: string, limit?: number | undefined | null, after?: number | undefined | null): EdgePageResult
  findNodesPaged(label: string, propKey: string, propValue: any, options?: FindNodesPagedOptions | undefined | null): IdPageResult
  findNodesByTimeRange(label: string, fromMs: number, toMs: number): Float64Array
  findNodesRange(label: string, propKey: string, lower?: PropertyRangeBound | undefined | null, upper?: PropertyRangeBound | undefined | null): Float64Array
  findNodesByTimeRangePaged(label: string, fromMs: number, toMs: number, options?: FindNodesByTimeRangePagedOptions | undefined | null): IdPageResult
  findNodesRangePaged(label: string, propKey: string, lower?: PropertyRangeBound | undefined | null, upper?: PropertyRangeBound | undefined | null, options?: FindNodesRangePagedOptions | undefined | null): PropertyRangePageResult
  personalizedPagerank(seedNodeIds: Array<number>, options?: PersonalizedPagerankOptions | undefined | null): PprResult
  exportAdjacency(options?: ExportOptions | undefined | null): AdjacencyExport
  neighborsPaged(nodeId: number, options?: NeighborsPagedOptions | undefined | null): NeighborPageResult
  connectedComponents(options?: ConnectedComponentsOptions | undefined | null): Array<ComponentEntry>
  componentOf(nodeId: number, options?: ComponentOfOptions | undefined | null): Float64Array
  vectorSearch(mode: string, options: VectorSearchOptions): Array<VectorHit>
  /**
   * Force an immediate WAL fsync. In GroupCommit mode, blocks until all
   * buffered data is durable. In Immediate mode, this is a no-op.
   */
  sync(): void
  flush(): void
  ingestMode(): void
  endIngest(): CompactionStats | null
  compact(): CompactionStats | null
  /**
   * Compact with a progress callback. The callback receives a progress object
   * and should return `true` to continue or `false` to cancel.
   * Runs synchronously. Blocks the event loop.
   */
  compactWithProgress(callback: (progress: CompactionProgress) => boolean): CompactionStats | null
  stats(): DbStats
  scrub(): ScrubReport
  closeAsync(options?: CloseOptions | undefined | null): Promise<void>
  statsAsync(): Promise<DbStats>
  scrubAsync(): Promise<ScrubReport>
  ensureNodeLabelAsync(label: string): Promise<number>
  ensureEdgeLabelAsync(label: string): Promise<number>
  getNodeLabelIdAsync(label: string): Promise<number | null>
  getEdgeLabelIdAsync(label: string): Promise<number | null>
  getNodeLabelAsync(labelId: number): Promise<string | null>
  getEdgeLabelAsync(labelId: number): Promise<string | null>
  listNodeLabelsAsync(): Promise<Array<NodeLabelInfo>>
  listEdgeLabelsAsync(): Promise<Array<EdgeLabelInfo>>
  setNodeSchemaAsync(label: string, schema: import('./schema-types').NodeSchema, options?: SchemaSetOptions | null): Promise<import('./schema-types').NodeSchemaInfo>
  checkNodeSchemaAsync(label: string, schema: import('./schema-types').NodeSchema, options?: SchemaCheckOptions | null): Promise<import('./schema-types').SchemaValidationReport>
  dropNodeSchemaAsync(label: string): Promise<boolean>
  getNodeSchemaAsync(label: string): Promise<import('./schema-types').NodeSchemaInfo | null>
  listNodeSchemasAsync(): Promise<Array<import('./schema-types').NodeSchemaInfo>>
  setEdgeSchemaAsync(label: string, schema: import('./schema-types').EdgeSchema, options?: SchemaSetOptions | null): Promise<import('./schema-types').EdgeSchemaInfo>
  checkEdgeSchemaAsync(label: string, schema: import('./schema-types').EdgeSchema, options?: SchemaCheckOptions | null): Promise<import('./schema-types').SchemaValidationReport>
  dropEdgeSchemaAsync(label: string): Promise<boolean>
  getEdgeSchemaAsync(label: string): Promise<import('./schema-types').EdgeSchemaInfo | null>
  listEdgeSchemasAsync(): Promise<Array<import('./schema-types').EdgeSchemaInfo>>
  setGraphSchemaAsync(schema: import('./schema-types').GraphSchema, options?: SchemaSetOptions | null): Promise<import('./schema-types').GraphSchemaPublishResult>
  alterGraphSchemaAsync(operations: Array<import('./schema-types').GraphSchemaOperation>, options?: SchemaSetOptions | null): Promise<import('./schema-types').GraphSchemaPublishResult>
  checkGraphSchemaSetAsync(schema: import('./schema-types').GraphSchema, options?: SchemaCheckOptions | null): Promise<import('./schema-types').GraphSchemaCheckReport>
  checkGraphSchemaAddAsync(schema: import('./schema-types').GraphSchema, options?: SchemaCheckOptions | null): Promise<import('./schema-types').GraphSchemaCheckReport>
  dropGraphSchemaAsync(): Promise<import('./schema-types').GraphSchemaPublishResult>
  upsertNodeAsync(labels: string | string[], key: string, options?: UpsertNodeOptions | null): Promise<number>
  addNodeLabelAsync(nodeId: number, label: string): Promise<boolean>
  removeNodeLabelAsync(nodeId: number, label: string): Promise<boolean>
  upsertEdgeAsync(from: number, to: number, label: string, options?: UpsertEdgeOptions | undefined | null): Promise<number>
  batchUpsertNodesAsync(nodes: Array<NodeInput>): Promise<Float64Array>
  batchUpsertEdgesAsync(edges: Array<EdgeInput>): Promise<Float64Array>
  batchUpsertNodesBinaryAsync(buffer: Buffer): Promise<Float64Array>
  batchUpsertEdgesBinaryAsync(buffer: Buffer): Promise<Float64Array>
  getNodeAsync(id: number): Promise<NodeView | null>
  getEdgeAsync(id: number): Promise<EdgeView | null>
  getNodeByKeyAsync(label: string, key: string): Promise<NodeView | null>
  getEdgeByTripleAsync(from: number, to: number, label: string): Promise<EdgeView | null>
  getNodesAsync(ids: Array<number>): Promise<Array<NodeView | null>>
  getNodesByKeysAsync(keys: Array<KeyQuery>): Promise<Array<NodeView | null>>
  getEdgesAsync(ids: Array<number>): Promise<Array<EdgeView | null>>
  deleteNodeAsync(id: number): Promise<void>
  deleteEdgeAsync(id: number): Promise<void>
  invalidateEdgeAsync(id: number, validTo: number): Promise<EdgeView | null>
  graphPatchAsync(patch: GraphPatch): Promise<PatchResult>
  pruneAsync(policy: PrunePolicy): Promise<PruneResult>
  neighborsAsync(nodeId: number, options?: NeighborsOptions | undefined | null): Promise<Array<NeighborEntry>>
  traverseAsync(startNodeId: number, maxDepth: number, options?: TraverseOptions | undefined | null): Promise<TraversalPageResult>
  topKNeighborsAsync(nodeId: number, k: number, options?: TopKNeighborsOptions | undefined | null): Promise<Array<NeighborEntry>>
  extractSubgraphAsync(startNodeId: number, maxDepth: number, options?: ExtractSubgraphOptions | undefined | null): Promise<SubgraphResult>
  findNodesAsync(label: string, propKey: string, propValue: any): Promise<Float64Array>
  queryNodeIdsAsync(request: import('./query-types').QueryNodeRequest): Promise<IdPageResult>
  queryNodesAsync(request: import('./query-types').QueryNodeRequest): Promise<NodePageResult>
  queryEdgeIdsAsync(request: import('./query-types').QueryEdgeRequest): Promise<IdPageResult>
  queryEdgesAsync(request: import('./query-types').QueryEdgeRequest): Promise<EdgePageResult>
  queryGraphRowsAsync(request: import('./query-types').GraphRowRequest): Promise<import('./query-types').GraphRowResult>
  queryGraphPipelineAsync(request: import('./query-types').GraphPipelineRequest): Promise<import('./query-types').GraphPipelineResult>
  explainNodeQueryAsync(request: import('./query-types').QueryNodeRequest): Promise<import('./query-types').QueryPlan>
  explainEdgeQueryAsync(request: import('./query-types').QueryEdgeRequest): Promise<import('./query-types').QueryPlan>
  explainGraphRowsAsync(request: import('./query-types').GraphRowRequest): Promise<import('./query-types').GraphRowExplain>
  explainGraphPipelineAsync(request: import('./query-types').GraphPipelineRequest): Promise<import('./query-types').GraphPipelineExplain>
  executeGqlAsync(query: string, params?: import('./query-types').GqlParams | null, options?: import('./query-types').GqlExecutionOptions | null): Promise<import('./query-types').GqlExecutionResult>
  explainGqlAsync(query: string, params?: import('./query-types').GqlParams | null, options?: import('./query-types').GqlExecutionOptions | null): Promise<import('./query-types').GqlExecutionExplain>
  ensureNodePropertyIndexAsync(label: string, spec: SecondaryIndexSpec): Promise<NodePropertyIndexInfo>
  dropNodePropertyIndexAsync(label: string, spec: SecondaryIndexSpec): Promise<boolean>
  listNodePropertyIndexesAsync(): Promise<Array<NodePropertyIndexInfo>>
  ensureEdgePropertyIndexAsync(label: string, spec: SecondaryIndexSpec): Promise<EdgePropertyIndexInfo>
  dropEdgePropertyIndexAsync(label: string, spec: SecondaryIndexSpec): Promise<boolean>
  listEdgePropertyIndexesAsync(): Promise<Array<EdgePropertyIndexInfo>>
  findNodesRangeAsync(label: string, propKey: string, lower?: PropertyRangeBound | undefined | null, upper?: PropertyRangeBound | undefined | null): Promise<Float64Array>
  findNodesRangePagedAsync(label: string, propKey: string, lower?: PropertyRangeBound | undefined | null, upper?: PropertyRangeBound | undefined | null, options?: FindNodesRangePagedOptions | undefined | null): Promise<PropertyRangePageResult>
  getNodesByLabelsAsync(labels: string | string[]): Promise<Array<NodeView>>
  getEdgesByLabelAsync(label: string): Promise<Array<EdgeView>>
  countNodesByLabelsAsync(labels: string | string[]): Promise<number>
  countEdgesByLabelAsync(label: string): Promise<number>
  nodesByLabelsAsync(labels: string | string[]): Promise<Float64Array>
  edgesByLabelAsync(label: string): Promise<Float64Array>
  neighborsBatchAsync(nodeIds: Array<number>, options?: NeighborsBatchOptions | undefined | null): Promise<Array<NeighborBatchEntry>>
  degreeAsync(nodeId: number, options?: DegreeOptions | undefined | null): Promise<number>
  sumEdgeWeightsAsync(nodeId: number, options?: SumEdgeWeightsOptions | undefined | null): Promise<number>
  avgEdgeWeightAsync(nodeId: number, options?: AvgEdgeWeightOptions | undefined | null): Promise<number | null>
  degreesAsync(nodeIds: Array<number>, options?: DegreesOptions | undefined | null): Promise<Array<DegreeBatchEntry>>
  shortestPathAsync(from: number, to: number, options?: ShortestPathOptions | undefined | null): Promise<ShortestPath | null>
  isConnectedAsync(from: number, to: number, options?: IsConnectedOptions | undefined | null): Promise<boolean>
  allShortestPathsAsync(from: number, to: number, options?: AllShortestPathsOptions | undefined | null): Promise<Array<ShortestPath>>
  nodesByLabelsPagedAsync(labels: string | string[], limit?: number | null, after?: number | null): Promise<IdPageResult>
  edgesByLabelPagedAsync(label: string, limit?: number | undefined | null, after?: number | undefined | null): Promise<IdPageResult>
  getNodesByLabelsPagedAsync(labels: string | string[], limit?: number | null, after?: number | null): Promise<NodePageResult>
  getEdgesByLabelPagedAsync(label: string, limit?: number | undefined | null, after?: number | undefined | null): Promise<EdgePageResult>
  findNodesPagedAsync(label: string, propKey: string, propValue: any, options?: FindNodesPagedOptions | undefined | null): Promise<IdPageResult>
  findNodesByTimeRangeAsync(label: string, fromMs: number, toMs: number): Promise<Float64Array>
  findNodesByTimeRangePagedAsync(label: string, fromMs: number, toMs: number, options?: FindNodesByTimeRangePagedOptions | undefined | null): Promise<IdPageResult>
  personalizedPagerankAsync(seedNodeIds: Array<number>, options?: PersonalizedPagerankOptions | undefined | null): Promise<PprResult>
  exportAdjacencyAsync(options?: ExportOptions | undefined | null): Promise<AdjacencyExport>
  neighborsPagedAsync(nodeId: number, options?: NeighborsPagedOptions | undefined | null): Promise<NeighborPageResult>
  connectedComponentsAsync(options?: ConnectedComponentsOptions | undefined | null): Promise<Array<ComponentEntry>>
  componentOfAsync(nodeId: number, options?: ComponentOfOptions | undefined | null): Promise<Float64Array>
  vectorSearchAsync(mode: string, options: VectorSearchOptions): Promise<Array<VectorHit>>
  syncAsync(): Promise<void>
  flushAsync(): Promise<void>
  ingestModeAsync(): Promise<void>
  endIngestAsync(): Promise<CompactionStats | null>
  compactAsync(): Promise<CompactionStats | null>
  /**
   * Async compaction with a fire-and-forget progress callback.
   * The callback receives progress updates but cannot cancel compaction (unlike the sync version).
   * Note: the database write lock is held for the entire compaction, so other operations on this
   * instance will block until compaction completes. The JS event loop remains responsive.
   */
  compactWithProgressAsync(callback: (progress: CompactionProgress) => void): Promise<CompactionStats | null>
}

export declare class SubgraphResult {
  get nodes(): Array<NodeView>
  get edges(): Array<EdgeView>
}

export declare class WriteTxn {
  upsertNode(labels: string | string[], key: string, options?: UpsertNodeOptions | null): TxnNodeRef
  upsertNodeAs(alias: string, labels: string | string[], key: string, options?: UpsertNodeOptions | null): TxnNodeRef
  addNodeLabel(target: TxnNodeRef, label: string): boolean
  removeNodeLabel(target: TxnNodeRef, label: string): boolean
  upsertEdge(from: TxnNodeRef, to: TxnNodeRef, label: string, options?: UpsertEdgeOptions | undefined | null): TxnEdgeRef
  upsertEdgeAs(alias: string, from: TxnNodeRef, to: TxnNodeRef, label: string, options?: UpsertEdgeOptions | undefined | null): TxnEdgeRef
  deleteNode(target: TxnNodeRef): void
  deleteEdge(target: TxnEdgeRef): void
  invalidateEdge(target: TxnEdgeRef, validTo: number): void
  stage(operations: Array<{ op: 'upsertNode'; alias?: string; labels: string | string[]; key: string; props?: Record<string, any>; weight?: number; denseVector?: Array<number>; sparseVector?: Array<SparseEntry> } | { op: 'upsertEdge'; alias?: string; from: TxnNodeRef; to: TxnNodeRef; label: string; props?: Record<string, any>; weight?: number; validFrom?: number; validTo?: number } | { op: 'deleteNode'; target: TxnEdgeOrNodeRef } | { op: 'deleteEdge'; target: TxnEdgeOrNodeRef } | { op: 'invalidateEdge'; target: TxnEdgeOrNodeRef; validTo: number }>): void
  getNode(target: TxnNodeRef): TxnNodeView | null
  getEdge(target: TxnEdgeRef): TxnEdgeView | null
  getNodeByKey(label: string, key: string): TxnNodeView | null
  getEdgeByTriple(from: TxnNodeRef, to: TxnNodeRef, label: string): TxnEdgeView | null
  commit(): TxnCommitResult
  rollback(): void
  upsertNodeAsync(labels: string | string[], key: string, options?: UpsertNodeOptions | null): Promise<TxnNodeRef>
  upsertNodeAsAsync(alias: string, labels: string | string[], key: string, options?: UpsertNodeOptions | null): Promise<TxnNodeRef>
  addNodeLabelAsync(target: TxnNodeRef, label: string): Promise<boolean>
  removeNodeLabelAsync(target: TxnNodeRef, label: string): Promise<boolean>
  upsertEdgeAsync(from: TxnNodeRef, to: TxnNodeRef, label: string, options?: UpsertEdgeOptions | undefined | null): Promise<TxnEdgeRef>
  upsertEdgeAsAsync(alias: string, from: TxnNodeRef, to: TxnNodeRef, label: string, options?: UpsertEdgeOptions | undefined | null): Promise<TxnEdgeRef>
  deleteNodeAsync(target: TxnNodeRef): Promise<void>
  deleteEdgeAsync(target: TxnEdgeRef): Promise<void>
  invalidateEdgeAsync(target: TxnEdgeRef, validTo: number): Promise<void>
  stageAsync(operations: Array<{ op: 'upsertNode'; alias?: string; labels: string | string[]; key: string; props?: Record<string, any>; weight?: number; denseVector?: Array<number>; sparseVector?: Array<SparseEntry> } | { op: 'upsertEdge'; alias?: string; from: TxnNodeRef; to: TxnNodeRef; label: string; props?: Record<string, any>; weight?: number; validFrom?: number; validTo?: number } | { op: 'deleteNode'; target: TxnEdgeOrNodeRef } | { op: 'deleteEdge'; target: TxnEdgeOrNodeRef } | { op: 'invalidateEdge'; target: TxnEdgeOrNodeRef; validTo: number }>): Promise<void>
  getNodeAsync(target: TxnNodeRef): Promise<TxnNodeView | null>
  getEdgeAsync(target: TxnEdgeRef): Promise<TxnEdgeView | null>
  getNodeByKeyAsync(label: string, key: string): Promise<TxnNodeView | null>
  getEdgeByTripleAsync(from: TxnNodeRef, to: TxnNodeRef, label: string): Promise<TxnEdgeView | null>
  commitAsync(): Promise<TxnCommitResult>
  rollbackAsync(): Promise<void>
}

export interface AdjacencyExport {
  nodeIds: Float64Array
  edgeLabels: Array<string>
  edgeFrom: Float64Array
  edgeTo: Float64Array
  edgeLabelIndexes: Uint32Array
  edgeWeights?: Float64Array
}

export interface AllShortestPathsOptions {
  direction?: string
  edgeLabelFilter?: Array<string>
  weightField?: string
  atEpoch?: number
  maxDepth?: number
  maxCost?: number
  maxPaths?: number
}

export interface AvgEdgeWeightOptions {
  direction?: string
  edgeLabelFilter?: Array<string>
  atEpoch?: number
}

export interface CloseOptions {
  /** If true, cancel any in-progress background compaction instead of waiting. */
  force?: boolean
}

export interface CompactionProgress {
  phase: string
  segmentsProcessed: number
  totalSegments: number
  recordsProcessed: number
  totalRecords: number
}

export interface CompactionStats {
  segmentsMerged: number
  nodesKept: number
  nodesRemoved: number
  edgesKept: number
  edgesRemoved: number
  durationMs: number
  outputSegmentId: number
  /** Number of nodes auto-pruned by registered compaction policies. */
  nodesAutoPruned: number
  /** Number of edges cascade-dropped due to auto-pruned nodes. */
  edgesAutoPruned: number
}

export interface ComponentEntry {
  nodeId: number
  componentId: number
}

export interface ComponentOfOptions {
  edgeLabelFilter?: Array<string>
  nodeLabelFilter?: NodeLabelFilter
  atEpoch?: number
}

export interface ComponentScrubFinding {
  componentKind: string
  findingType: string
  detail: string
}

export interface ConnectedComponentsOptions {
  edgeLabelFilter?: Array<string>
  nodeLabelFilter?: NodeLabelFilter
  atEpoch?: number
}

export interface DbOptions {
  createIfMissing?: boolean
  edgeUniqueness?: boolean
  memtableFlushThreshold?: number
  /** Trigger compaction automatically after this many flushes. Default 4, 0 = disabled. */
  compactAfterNFlushes?: number
  denseVector?: DenseVectorConfig
  /** WAL sync mode: 'immediate' or 'group-commit' (default). */
  walSyncMode?: string
  /** Group commit sync interval in milliseconds. Default: 50. */
  groupCommitIntervalMs?: number
  /** Hard cap on memtable size in bytes. Writes trigger a flush when exceeded. 0 = disabled. */
  memtableHardCapBytes?: number
  /**
   * Maximum number of immutable memtables pending flush before writers block.
   * Default: 4. Set to 0 to disable immutable count backpressure.
   */
  maxImmutableMemtables?: number
}

export interface DbStats {
  /** Bytes buffered in WAL but not yet fsynced. Always 0 in immediate mode. */
  pendingWalBytes: number
  /** Number of on-disk segments. */
  segmentCount: number
  /** Node tombstones in the memtable. */
  nodeTombstoneCount: number
  /** Edge tombstones in the memtable. */
  edgeTombstoneCount: number
  /** Timestamp (ms since epoch) of last completed compaction, or null. */
  lastCompactionMs?: number
  /** WAL sync mode: "immediate" or "group-commit". */
  walSyncMode: string
  /** Estimated bytes in the active (mutable) memtable. */
  activeMemtableBytes: number
  /** Estimated bytes across all immutable memtables pending flush. */
  immutableMemtableBytes: number
  /** Number of immutable memtables pending flush. */
  immutableMemtableCount: number
  /** Number of flush operations currently in flight. */
  pendingFlushCount: number
  /** The WAL generation ID currently being written to. */
  activeWalGenerationId: number
  /** The oldest WAL generation ID still retained for recovery. */
  oldestRetainedWalGenerationId: number
}

export interface DegreeBatchEntry {
  nodeId: number
  degree: number
}

export interface DegreeOptions {
  direction?: string
  edgeLabelFilter?: Array<string>
  atEpoch?: number
}

export interface DegreesOptions {
  direction?: string
  edgeLabelFilter?: Array<string>
  atEpoch?: number
}

export interface DenseVectorConfig {
  dimension: number
  metric?: string
}

export interface EdgeInput {
  from: number
  to: number
  label: string
  props?: Record<string, any>
  weight?: number
  validFrom?: number
  validTo?: number
}

export interface EdgeInvalidation {
  edgeId: number
  validTo: number
}

export interface EdgeLabelInfo {
  label: string
  labelId: number
}

export interface EdgePropertyIndexInfo {
  indexId: number
  label: string
  fields: Array<SecondaryIndexField>
  kind: SecondaryIndexKind
  state: 'building' | 'ready' | 'failed'
  lastError: string | null
  compound: boolean
}

export interface ExportOptions {
  nodeLabelFilter?: NodeLabelFilter
  edgeLabelFilter?: Array<string>
  includeWeights?: boolean
}

export interface ExtractSubgraphOptions {
  direction?: string
  edgeLabelFilter?: Array<string>
  nodeLabelFilter?: NodeLabelFilter
  atEpoch?: number
}

export interface FindNodesByTimeRangePagedOptions {
  limit?: number
  after?: number
}

export interface FindNodesPagedOptions {
  limit?: number
  after?: number
}

export interface FindNodesRangePagedOptions {
  limit?: number
  after?: PropertyRangeCursor
}

export interface GqlExecutionOptionsInput {
  mode?: string
  allowFullScan?: boolean
  maxRows?: number
  cursor?: string
  maxCursorBytes?: number
  maxMutationRows?: number
  maxMutationOps?: number
  maxPipelineRows?: number
  maxGroups?: number
  maxCollectItems?: number
  maxUnionBranches?: number
  maxSubqueryInvocations?: number
  maxSubqueryDepth?: number
  maxShortestPathPairs?: number
  maxIntermediateBindings?: number
  maxFrontier?: number
  maxPathHops?: number
  maxPathsPerStart?: number
  maxOrderMaterialization?: number
  maxSkip?: number
  maxQueryBytes?: number
  maxParamBytes?: number
  maxAstDepth?: number
  maxLiteralItems?: number
  includePlan?: boolean
  profile?: boolean
  compactRows?: boolean
  includeVectors?: boolean
}

export interface GraphPatch {
  upsertNodes?: Array<NodeInput>
  upsertEdges?: Array<EdgeInput>
  invalidateEdges?: Array<EdgeInvalidation>
  deleteNodeIds?: Array<number>
  deleteEdgeIds?: Array<number>
}

export interface IdPageResult {
  items: Float64Array
  nextCursor?: number
}

export interface IsConnectedOptions {
  direction?: string
  edgeLabelFilter?: Array<string>
  atEpoch?: number
  maxDepth?: number
}

export interface KeyQuery {
  label: string
  key: string
}

export interface NamedPrunePolicy {
  name: string
  policy: PrunePolicy
}

export interface NeighborBatchEntry {
  queryNodeId: number
  neighbors: Array<NeighborEntry>
}

/** A single neighbor entry as a plain JS object. */
export interface NeighborEntry {
  nodeId: number
  edgeId: number
  label: string
  weight: number
  validFrom: number
  validTo: number
}

export interface NeighborsBatchOptions {
  direction?: string
  edgeLabelFilter?: Array<string>
  atEpoch?: number
  decayLambda?: number
}

export interface NeighborsOptions {
  direction?: string
  edgeLabelFilter?: Array<string>
  limit?: number
  atEpoch?: number
  decayLambda?: number
}

export interface NeighborsPagedOptions {
  direction?: string
  edgeLabelFilter?: Array<string>
  limit?: number
  after?: number
  atEpoch?: number
  decayLambda?: number
}

export interface NodeInput {
  labels: string | string[]
  key: string
  props?: Record<string, any>
  weight?: number
  denseVector?: Array<number>
  sparseVector?: Array<SparseEntry>
}

export interface NodeLabelFilter {
  labels: Array<string>
  mode: 'any' | 'all'
}

export interface NodeLabelInfo {
  label: string
  labelId: number
}

export interface NodePropertyIndexInfo {
  indexId: number
  label: string
  fields: Array<SecondaryIndexField>
  kind: SecondaryIndexKind
  state: 'building' | 'ready' | 'failed'
  lastError: string | null
  compound: boolean
}

export interface PatchResult {
  nodeIds: Float64Array
  edgeIds: Float64Array
}

export interface PersonalizedPagerankOptions {
  algorithm?: string
  dampingFactor?: number
  maxIterations?: number
  epsilon?: number
  approxResidualTolerance?: number
  edgeLabelFilter?: Array<string>
  maxResults?: number
}

export interface PprApproxMeta {
  residualTolerance: number
  pushes: number
  maxRemainingResidual: number
}

export interface PprResult {
  nodeIds: Float64Array
  scores: Float64Array
  iterations: number
  converged: boolean
  algorithm: string
  approx?: PprApproxMeta
}

export interface PropertyRangeBound {
  value: number
  inclusive?: boolean
  domain: string
}

export interface PropertyRangeCursor {
  value: number
  nodeId: number
  domain: string
}

export interface PropertyRangePageResult {
  items: Float64Array
  nextCursor?: PropertyRangeCursor
}

export interface PrunePolicy {
  /** Prune nodes older than this many milliseconds. Optional. */
  maxAgeMs?: number
  /** Prune nodes with weight <= this threshold. Optional. */
  maxWeight?: number
  /** Scope to a single node label. Optional. */
  label?: string
}

export interface PruneResult {
  /** Number of nodes pruned. */
  nodesPruned: number
  /** Number of edges cascade-deleted. */
  edgesPruned: number
}

export interface SchemaCheckOptions {
  maxViolations?: number
  chunkSize?: number
  scanLimit?: number | null
}

export interface SchemaSetOptions {
  maxViolations?: number
  chunkSize?: number
  scanLimit?: number | null
}

export interface ScrubReport {
  segments: Array<SegmentScrubResult>
  totalComponentsChecked: number
  totalComponentsOk: number
  totalComponentsFailed: number
  totalBytesDigested: number
  durationMs: number
}

export type SecondaryIndexKind = 'equality' | 'range'
export type NodeMetadataIndexField = 'id' | 'key' | 'weight' | 'created_at' | 'updated_at'
export type EdgeMetadataIndexField =
  | 'id'
  | 'from'
  | 'to'
  | 'weight'
  | 'created_at'
  | 'updated_at'
  | 'valid_from'
  | 'valid_to'
export interface SecondaryIndexPropertyField {
  source: 'property'
  key: string
}
export interface SecondaryIndexMetadataField {
  source: 'metadata'
  field: NodeMetadataIndexField | EdgeMetadataIndexField
}
export type SecondaryIndexField =
  | SecondaryIndexPropertyField
  | SecondaryIndexMetadataField

export interface SecondaryIndexSpec {
  fields: Array<SecondaryIndexField>
  kind: SecondaryIndexKind
}

export interface SegmentScrubResult {
  segmentId: number
  findings: Array<ComponentScrubFinding>
  componentsOk: number
  bytesDigested: number
}

export interface ShortestPath {
  nodes: Array<number>
  edges: Array<number>
  totalCost: number
}

export interface ShortestPathOptions {
  direction?: string
  edgeLabelFilter?: Array<string>
  weightField?: string
  atEpoch?: number
  maxDepth?: number
  maxCost?: number
}

export interface SparseEntry {
  dimension: number
  value: number
}

export interface SumEdgeWeightsOptions {
  direction?: string
  edgeLabelFilter?: Array<string>
  atEpoch?: number
}

export interface TopKNeighborsOptions {
  direction?: string
  edgeLabelFilter?: Array<string>
  scoring?: string
  decayLambda?: number
  atEpoch?: number
}

export interface TraversalCursor {
  depth: number
  lastNodeId: number
}

export interface TraversalHit {
  nodeId: number
  depth: number
  viaEdgeId?: number
  score?: number
}

export interface TraversalPageResult {
  items: Array<TraversalHit>
  nextCursor?: TraversalCursor
}

export interface TraverseOptions {
  minDepth?: number
  direction?: string
  edgeLabelFilter?: Array<string>
  emitNodeLabelFilter?: NodeLabelFilter
  atEpoch?: number
  decayLambda?: number
  limit?: number
  cursor?: TraversalCursor
}

export interface TxnCommitResult {
  nodeIds: Float64Array
  edgeIds: Float64Array
  nodeAliases: Record<string, number>
  edgeAliases: Record<string, number>
}

export interface TxnEdgeOrNodeRef {
  id?: number
  labels?: string | string[]
  label?: string
  key?: string
  local?: string
  from?: TxnNodeRef
  to?: TxnNodeRef
}

export interface TxnEdgeRef {
  id?: number
  from?: TxnNodeRef
  to?: TxnNodeRef
  label?: string
  local?: string
}

export interface TxnEdgeView {
  id?: number
  local?: string
  from: TxnNodeRef
  to: TxnNodeRef
  label: string
  props: Record<string, any>
  createdAt?: number
  updatedAt?: number
  weight: number
  validFrom?: number
  validTo?: number
}

export interface TxnNodeRef {
  id?: number
  labels?: string | string[]
  key?: string
  local?: string
}

export interface TxnNodeView {
  id?: number
  local?: string
  labels: Array<string>
  key: string
  props: Record<string, any>
  createdAt?: number
  updatedAt?: number
  weight: number
  denseVector?: Array<number>
  sparseVector?: Array<SparseEntry>
}

export interface UpsertEdgeOptions {
  props?: Record<string, any>
  weight?: number
  validFrom?: number
  validTo?: number
}

export interface UpsertNodeOptions {
  props?: Record<string, any>
  weight?: number
  denseVector?: Array<number>
  sparseVector?: Array<SparseEntry>
}

export interface VectorHit {
  nodeId: number
  score: number
}

export interface VectorSearchOptions {
  k: number
  denseQuery?: Array<number>
  sparseQuery?: Array<SparseEntry>
  labelFilter?: NodeLabelFilter
  efSearch?: number
  scope?: VectorSearchScope
  denseWeight?: number
  sparseWeight?: number
  fusionMode?: string
}

export interface VectorSearchScope {
  startNodeId: number
  maxDepth: number
  direction?: string
  edgeLabelFilter?: Array<string>
  atEpoch?: number
}
